### ISSUE TITLE
Test material compile fails but running tests is attempted

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/TKG#126] opened 2020-12-04 18:14 UTC
I noticed that even when the test material fails to compile and this portion of the build fails, running the tests are still attempted.

https://ci.eclipse.org/openj9/job/Grinder/1256/
```
13:03:32      [javac]   symbol:   variable MAC
13:03:32      [javac]   location: class XlpOptionsTestRunner
13:03:32      [javac] /Users/****/workspace/Grinder/openjdk-tests/functional/VM_Test/src/j9vm/test/xlp/XlpOptionsTestRunner.java:271: error: cannot find symbol
13:03:32      [javac] 			xlpOptionsList.add(new XlpOption("-Xlp:objectheap:pagesize=4M,pagesize=2M", 2 * ONE_MB, XlpUtil.XLP_PAGE_TYPE_NOT_USED, osName == MAC));
13:03:32      [javac] 			                                                                                                                                  ^
13:03:32      [javac]   symbol:   variable MAC
13:03:32      [javac]   location: class XlpOptionsTestRunner
13:03:32      [javac] Note: Some input files use or override a deprecated API.
13:03:32      [javac] Note: Recompile with -Xlint:deprecation for details.
13:03:32      [javac] Note: Some input files use unchecked or unsafe operations.
13:03:32      [javac] Note: Recompile with -Xlint:unchecked for details.
13:03:32      [javac] 5 errors
13:03:32      [javac] 41 warnings
13:03:32  
13:03:32  BUILD FAILED
13:03:32  /Users/****/workspace/Grinder/openjdk-tests/TKG/scripts/build_test.xml:60: The following error occurred while executing this line:
13:03:32  /Users/****/workspace/Grinder/openjdk-tests/functional/VM_Test/build.xml:214: The following error occurred while executing this line:
13:03:32  /Users/****/workspace/Grinder/openjdk-tests/functional/VM_Test/build.xml:110: Compile failed; see the compiler error output for details.
13:03:32  
13:03:32  Total time: 12 seconds
13:03:32  1
13:03:32  make[1]: *** [compile] Error 1
13:03:32  make: *** [compile] Error 2
13:03:32  + '[' '!' -z 0 ']'
13:03:32  + '[' darwin15.6.0 = cygwin ']'
13:03:32  + echo PROCESSCATCH: Checking for any leftover java processes on the machine
13:03:32  PROCESSCATCH: Checking for any leftover java processes on the machine
13:03:32  + ps -fu ****
13:03:32  + grep java
13:03:32  + egrep -v 'remoting.jar|agent.jar|grep'
13:03:32    502 47421 47420   0  9:10PM ??         3:52.80 java -jar slave.jar
13:03:32  + echo PROCESSCATCH: There are rogue processes still on the machine as per the list above
13:03:32  PROCESSCATCH: There are rogue processes still on the machine as per the list above
[Pipeline] }
13:03:34  $ ssh-agent -k
13:03:34  unset SSH_AUTH_SOCK;
13:03:34  unset SSH_AGENT_PID;
13:03:34  echo Agent pid 85305 killed;
13:03:38  [ssh-agent] Stopped.
[Pipeline] // sshagent
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Test)
[Pipeline] timestamps
[Pipeline] {
[Pipeline] echo
13:03:42  Running tests...
[Pipeline] echo
13:03:42  ITERATION: 1/1
[Pipeline] sh
13:03:46  ++ uname
13:03:46  + '[' Darwin = AIX ']'
13:03:46  ++ uname
13:03:46  + '[' Darwin = SunOS ']'
13:03:46  + MAKE=make
13:03:46  + make -f ./openjdk-tests/TKG/testEnv.mk testEnvTeardown
13:03:46  make: Nothing to be done for `testEnvTeardown'.
[Pipeline] sh
13:03:54  + ./openjdk-tests/maketest.sh ./openjdk-tests _testList TESTLIST=xlpTests_1,xlpCodeCacheTests_1
13:03:54  JAVA_HOME is set to /Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image
13:03:54  /Users/jenkins/Xcode7/Xcode.app/Contents/Developer/usr/bin/make -f makeGen.mk AUTO_DETECT=true MODE=tests TESTTARGET=testList TESTLIST=xlpTests_1,xlpCodeCacheTests_1
13:03:54  perl scripts/configure.pl
13:03:54  /Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java -cp "./bin/TestKitGen.jar:./lib/json-simple.jar" org.testKitGen.MainRunner --mode=tests --spec=osx_x86-64_cmprssptrs --jdkVersion=8 --impl=openj9 --buildList=functional/VM_Test --iterations=1 --testFlag= --testTarget=testList --testList=xlpTests_1,xlpCodeCacheTests_1 --numOfMachines=1 --testTime= --TRSSURL= 
13:03:54  Modes data parsed from resources/modes.xml and resources/ottawa.csv.
13:03:54  
13:03:54  Starting to generate test make files.
13:03:54  
13:03:54  Parsing /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../functional/VM_Test/playlist.xml
13:03:54  
13:03:54  Generated /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../functional/VM_Test/autoGen.mk
13:03:54  
13:03:54  Generated /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../functional/autoGen.mk
13:03:54  
13:03:54  Generated /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../autoGen.mk
13:03:54  
13:03:54  Generated /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/utils.mk
13:03:54  
13:03:54  Make files are generated successfully.
13:03:54  
13:03:54  /Users/jenkins/Xcode7/Xcode.app/Contents/Developer/usr/bin/make -f runtest.mk _testList
13:03:54  
13:03:54  Running make 3.81
13:03:54  set TEST_ROOT to /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/..
13:03:54  set JDK_VERSION to 8
13:03:54  set JDK_IMPL to openj9
13:03:54  set JVM_VERSION to openjdk8-openj9
13:03:54  set JCL_VERSION to latest
13:03:54  set JAVA_HOME to /Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image
13:03:54  set SPEC to osx_x86-64_cmprssptrs
13:03:54  Running testList ...
13:03:54  There are 2 test targets in testList
13:03:54  "/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -version
13:03:54  openjdk version "1.8.0_282-internal"
13:03:54  OpenJDK Runtime Environment (build 1.8.0_282-internal-jenkins_2020_12_03_22_39-b00)
13:03:54  Eclipse OpenJ9 VM (build master-8401f565b48, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20201203_580 (JIT enabled, AOT enabled)
13:03:54  OpenJ9   - 8401f565b48
13:03:54  OMR      - f7a2761067b
13:03:54  JCL      - 0655969557f based on jdk8u282-b04)
13:03:54  
13:03:54  ===============================================
13:03:54  Running test xlpTests_1 ...
13:03:54  ===============================================
13:03:54  xlpTests_1 Start Time: Fri Dec  4 13:03:53 2020 Epoch Time (ms): 1607105033205
13:03:54  "/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";
13:03:54  
13:03:54  Attempting to destroy all caches in cacheDir /Users/jenkins/javasharedresources/
13:03:54  
13:03:54  JVMSHRC806I Compressed references persistent shared cache "sharedcc_jenkins" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
13:03:54  JVMSHRC005I No shared class caches available
13:03:54  cache cleanup done
13:03:54  variation: Mode610
13:03:54  JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:gencon 
13:03:54  { itercnt=1; \
13:03:54  	mkdir -p "/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16071050334664/xlpTests_1"; \
13:03:54  	cd "/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16071050334664/xlpTests_1"; \
13:03:54  	"/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -Dplatform=osx_x86-64_cr -cp "/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar" \
13:03:54  	j9vm.runner.Menu -test="j9vm.test.xlp" -exe=""/Users/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xdump" \
13:03:54  	-jar="/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../../jvmtest/functional/VM_Test/VM_Test.jar" \
13:03:54  	-xids=all,osx_x86-64_cr,; \
13:03:54  	if [ $? -eq 0 ] ; then echo ""; echo "xlpTests_1""_PASSED"; echo ""; cd /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/..;  else echo ""; echo "xlpTests_1""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/Users/jenkins/workspace/Grinder/openjdk-tests/TKG/../TKG/test_output_16071050334664/TestTargetResult";
13:03:54  Error: Could not find or load main class j9vm.runner.Menu
13:03:55  
13:03:55  xlpTests_1_FAILED
```

**Comment by sophia-guo** [comment] 2020-12-04 18:19
Duplicate of https://github.com/AdoptOpenJDK/openjdk-tests/issues/2068

**Closed** 2020-12-04 18:19 UTC
